{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nfs-shared-csi.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nfs-shared-csi.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nfs-shared-csi.fullname" . }}-node-role
  labels:
    {{- include "nfs-shared-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nfs-shared-csi.fullname" . }}-node-binding
  labels:
    {{- include "nfs-shared-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nfs-shared-csi.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "nfs-shared-csi.fullname" . }}-node-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
