{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "nfs-shared-csi.labels" . | nindent 4 }}
  {{- if .Values.storageClass.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ include "nfs-shared-csi.driverName" . }}
parameters:
  server: {{ required "storageClass.server is required when storageClass.create is true" .Values.storageClass.server | quote }}
  share: {{ required "storageClass.share is required when storageClass.create is true" .Values.storageClass.share | quote }}
  {{- range $key, $value := .Values.storageClass.parameters }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
{{- with .Values.storageClass.mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
