apiVersion: v2
name: nfs-shared-csi
description: A Helm chart for NFS CSI Driver for Kubernetes
type: application
version: 0.3.0
appVersion: "1.6.0"
keywords:
  - nfs
  - csi
  - storage
  - kubernetes
home: https://github.com/takutakahashi/nfs-shared-csi
sources:
  - https://github.com/takutakahashi/nfs-shared-csi
maintainers:
  - name: takutakahashi
kubeVersion: ">=1.20.0-0"
