apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: nfs.csi.example.com
spec:
  attachRequired: false
  podInfoOnMount: false
  fsGroupPolicy: None
  volumeLifecycleModes:
    - Persistent
