apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-nfs-node-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-nfs-node-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-nfs-node-binding
subjects:
  - kind: ServiceAccount
    name: csi-nfs-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-nfs-node-role
  apiGroup: rbac.authorization.k8s.io
